apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: srihari25/employee-service:v1
        command: ["java"]
        args: ["-jar","/wrong.jar"]
        ports:
        - containerPort: 8080